export const CONFIG = {
  PATHS: {
    API_BASE: "/api",
    SNIPPET: "/snippet",
    USER: "/user",
    TAG: "/tags",
    FOLDER: "/folder",
  },
  THEMES: [
    "amethyst-haze",
    "claude",
    "notebook",
    "bold-tech",
    "elegant-luxury",
    "t3-chat",
    "nature",
    "starry-night",
  ],
  LANGUAGES: [
    { label: "JavaScript", value: "javascript" },
    { label: "TypeScript", value: "typescript" },
    { label: "Python", value: "python" },
    { label: "Java", value: "java" },
    { label: "HTML", value: "html" },
    { label: "CSS", value: "css" },
    { label: "JSON", value: "json" },
    { label: "XML", value: "xml" },
    { label: "Markdown", value: "markdown" },
    { label: "PHP", value: "php" },
    { label: "SQL", value: "sql" },
    { label: "Rust", value: "rust" },
    { label: "C++", value: "cpp" },
    { label: "Go", value: "go" },
    { label: "YAML", value: "yaml" },
  ],
};
