import hljs from "highlight.js/lib/core";
import bash from "highlight.js/lib/languages/bash";
import c from "highlight.js/lib/languages/c";
import cpp from "highlight.js/lib/languages/cpp";
import csharp from "highlight.js/lib/languages/csharp";
import css from "highlight.js/lib/languages/css";
// import cypher from "highlight.js/lib/languages/cypher";
import django from "highlight.js/lib/languages/django"; // Jinja2-style templating
import dockerfile from "highlight.js/lib/languages/dockerfile";
import elixir from "highlight.js/lib/languages/elixir";
import elm from "highlight.js/lib/languages/elm";
import erlang from "highlight.js/lib/languages/erlang";
import fsharp from "highlight.js/lib/languages/fsharp";
import go from "highlight.js/lib/languages/go";
import gradle from "highlight.js/lib/languages/gradle";
import graphql from "highlight.js/lib/languages/graphql";
import groovy from "highlight.js/lib/languages/groovy";
import handlebars from "highlight.js/lib/languages/handlebars";
import java from "highlight.js/lib/languages/java";
import javascript from "highlight.js/lib/languages/javascript";
import json from "highlight.js/lib/languages/json";
// import json5 from "highlight.js/lib/languages/json5";
import latex from "highlight.js/lib/languages/latex";
import latex2e from "highlight.js/lib/languages/latex";
import makefile from "highlight.js/lib/languages/makefile";
import markdown from "highlight.js/lib/languages/markdown";
import nginx from "highlight.js/lib/languages/nginx";
import objectivec from "highlight.js/lib/languages/objectivec";
import perl from "highlight.js/lib/languages/perl";
import php from "highlight.js/lib/languages/php";
import plaintext from "highlight.js/lib/languages/plaintext";
import powershell from "highlight.js/lib/languages/powershell";
import python from "highlight.js/lib/languages/python";
import qml from "highlight.js/lib/languages/qml";
// import qsharp from "highlight.js/lib/languages/qsharp";
import r from "highlight.js/lib/languages/r";
import ruby from "highlight.js/lib/languages/ruby";
import sql from "highlight.js/lib/languages/sql";
import typescript from "highlight.js/lib/languages/typescript";
import xml from "highlight.js/lib/languages/xml"; // for Blade, HTML
import html from "highlight.js/lib/languages/xml";
import yaml from "highlight.js/lib/languages/yaml";

// Register languages
hljs.registerLanguage("javascript", javascript);
hljs.registerLanguage("typescript", typescript);
hljs.registerLanguage("html", html);
hljs.registerLanguage("css", css);
hljs.registerLanguage("json", json);
hljs.registerLanguage("markdown", markdown);
hljs.registerLanguage("plaintext", plaintext);

hljs.registerLanguage("python", python);
hljs.registerLanguage("java", java);
hljs.registerLanguage("c", c);
hljs.registerLanguage("cpp", cpp);
hljs.registerLanguage("csharp", csharp);
hljs.registerLanguage("php", php);
hljs.registerLanguage("ruby", ruby);
hljs.registerLanguage("go", go);
hljs.registerLanguage("sql", sql);
hljs.registerLanguage("bash", bash);
hljs.registerLanguage("nginx", nginx);
hljs.registerLanguage("dockerfile", dockerfile);
// hljs.registerLanguage("json5", json5);

hljs.registerLanguage("graphql", graphql);
hljs.registerLanguage("yaml", yaml);
hljs.registerLanguage("makefile", makefile);
hljs.registerLanguage("latex", latex);
hljs.registerLanguage("powershell", powershell);
hljs.registerLanguage("objectivec", objectivec);
hljs.registerLanguage("perl", perl);
hljs.registerLanguage("elixir", elixir);
hljs.registerLanguage("erlang", erlang);
hljs.registerLanguage("elm", elm);
hljs.registerLanguage("fsharp", fsharp);
hljs.registerLanguage("groovy", groovy);
hljs.registerLanguage("gradle", gradle);
hljs.registerLanguage("handlebars", handlebars);
hljs.registerLanguage("xml", xml);
hljs.registerLanguage("django", django);
hljs.registerLanguage("latex2e", latex2e);
// hljs.registerLanguage("qsharp", qsharp);
hljs.registerLanguage("qml", qml);
hljs.registerLanguage("r", r);
// hljs.registerLanguage("cypher", cypher);

export default hljs;
